---
- hosts: all
  vars:
     - ansible_ssh_user: "{{ user }}"
     - ansible_ssh_pass: "{{ password }}"
     - ansible_ssh_port: "5985"
     - ansible_connection: "winrm"
  tasks:
   - name: check for windows update and install
     win_updates:
       category_names:
         -SecurityUpdates
         -CriticalUpdates
         -UpdateRollups
       state: installed
       log_path: c:\winupdate_vm.txt
       register: window_up
       
   - name: Restart the server if required
     win_reboot:
     when: window_up.reboot_required
