---
- hosts: all
  vars:
     - ansible_ssh_user: "{{ user }}"
     - ansible_ssh_pass: "{{ password }}"
     - ansible_ssh_port: "5985"
     - ansible_connection: "winrm"
  tasks:
   - name: check for windows update and install
     win_updates:
       category_names: DefinitionUpdates
       state: installed
     register: result
       
   - debug: var=result    
       
   - name: Restart the server if required
     win_reboot:
     when: result.reboot_required
